# Generated by Django 4.1.7 on 2023-04-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date'], 'verbose_name': '信息统计', 'verbose_name_plural': '信息统计'},
        ),
    ]
