# Generated by Django 4.1.7 on 2023-04-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date']},
        ),
    ]
